// Generated by scripts/build-babylon-runtime.mjs.
import '../assets/vendor/babylon-runtime.e0c2e4293914.min.js';

if (!globalThis.BABYLON) {
  throw new Error('Arena Babylon runtime failed to initialize');
}

export default globalThis.BABYLON;
